### ISSUE TITLE
Greynoise enrichment not working due to API change

### ISSUE THREAD

**Issue by MarcOverIP** [outflanknl/RedELK#171]
Greynoise enrichment is not working as Greynoise has deprecated the old API we were using.

They now have a community API: https://developer.greynoise.io/docs/using-the-greynoise-community-api 

Both the request as the output data is now different. Also, without API key (you get that upon registration) we are rate limited to 10 queries per day.

We should do at least the following:
1. modify our python code to adhere to the new API
2. check if the results from the API is sufficient for our use (perhaps the mere fact that "noise" : "true" is present, is sufficient. Although Im not sure what noise:true, classification:benign would mean). Optionally include the "link" value as hyperlink to make it clickable
3. Expand config.json with a greynoise API section. Not sure we as RedELK project should register a single API for all downloads. Let the end users of RedELK do that themselves.

**Comment by fastlorenzo** [comment]
I'll work on it, but I'm not sure what's the API rate limit for Community (https://developer.greynoise.io/discuss/60a21febb3fd7d00481177c5)

**Comment by MarcOverIP** [comment]
Greynoise api key in config file, just as we do with vt and the others? 

If no api key present (even possible), just yolo try?

**Comment by fastlorenzo** [comment]
fixed in #183

**Comment by fastlorenzo** [comment]
Still todo:
- [ ] Check the ES index and adapt to API change

**Comment by fastlorenzo** [comment]
@MarcOverIP now that Greynoise API is working, we'll be able to get correct data in ES and adapt the ES fields mapping to close this one as well 😄

**Comment by MarcOverIP** [comment]
Sadly this is not entirely working after pr #207. The following error is thrown:

``
2021-11-19 01:16:06,050 - ERROR - alarm - daemon.py - run_enrichments -- RequestError(400, 'x_content_parse_exception', '[1:212] [bool] failed to parse field [filter]')
Traceback (most recent call last):
  File "/usr/share/redelk/bin/daemon.py", line 69, in run_enrichments
    enrich_dict[enrich_module]['result'] = copy.deepcopy(module_class.run())
  File "/usr/share/redelk/bin/modules/enrich_greynoise/module.py", line 44, in run
    hits = self.enrich_greynoise()
  File "/usr/share/redelk/bin/modules/enrich_greynoise/module.py", line 94, in enrich_greynoise
    last_es_data = self.get_last_es_data(ip)
  File "/usr/share/redelk/bin/modules/enrich_greynoise/module.py", line 202, in get_last_es_data
    es_results = raw_search(es_query, index='redirtraffic-*')
  File "/usr/share/redelk/bin/modules/helpers.py", line 68, in raw_search
    es_result = es.search(index=index, body=query, size=size)
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch/client/utils.py", line 152, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch/client/__init__.py", line 1663, in search
    body=body,
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch/transport.py", line 392, in perform_request
    raise e
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch/transport.py", line 365, in perform_request
    timeout=timeout,
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch/connection/http_urllib3.py", line 269, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch/connection/base.py", line 313, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.RequestError: RequestError(400, 'x_content_parse_exception', '[1:212] [bool] failed to parse field [filter]')
``

Also pasting picture as formatting of the above is off

![image](https://user-images.githubusercontent.com/17198879/142533260-77521601-546c-4959-aed4-35057ac70edf.png)

**Comment by fastlorenzo** [comment]
Looks like am issue with es query, I'll che k the code

**Comment by MarcOverIP** [comment]
In latest install I don't see this fixed. Error is gone, but data is not there. Needs troubleshooting.

Im moving this to release v2.0.0-beta.6

**Comment by fastlorenzo** [comment]
Should be fixed in #262
