### ISSUE TITLE
LOGSTASH SSL INTERNAL ERROR WRONG VERSION NUMBER

### ISSUE THREAD

**Issue by trufardo** [outflanknl/RedELK#24]
I followed the instruction to set up redelk. I have my certificate based on ip address. I have kibana dashboard up but I don't see my team server logs and my redirs logs getting populated. When I dig deeper in logs, I found logstash is having ssl issue.

`Handling exception: javax.net.ssl.SSLHandshakeException: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER`

I added ssl_verify_mode => none in the 10-inputs.conf file but didn't help.
I change TLS to 1.2 an regenerate the certs but didn't help as well.
This is the new config.cnf the character "-" is because data cant be public.

```
[req]
default_bits = 2048
prompt = no
default_md = sha256
x509_extensions = v3_req
distinguished_name = dn

[dn]
C = -
ST = -
L = -
O = -
OU = -
CN = http://www.-
emailAddress = -

[v3_req]
subjectAltName = @alt_names

[alt_names]
DNS.1 = XXX.XXX.XXX.XXX
DNS.2 = XXX.XXX.XXX.XXX
IP.1 = XXX.XXX.XXX.XXX
```
Any tips? All is ubuntu  18.04 #16

**Comment by MarcOverIP** [comment]
TLS issues are amongst the most common we experience as well. Sadly, the error messages are just too cryptic.

A few things to check are:
- Did the installer packages output any errors? You can check their log files in same dir you ran the installers.
- Did you deploy the certificates at both logstash (redelek server) and filebeat (redirs and c2 servers) locations after regenerating?
- Check the filebeat log file for errors.
- Did you run the filebeat installer with the right hostname/ip as parameter? You can check and change it in the /etc/filebeat/filebeat.yml config

**Comment by trufardo** [comment]
Thanks for the answer, i check all the things that u said, move the new certs, installer dont output any error, the filebeat log have no errors, i correctly install filebeat with the ip public and the port correctly of the redelk server.
I changed the filebeat.yml and add `ssl.enabled: true` but the same logstash fail
```
[2020-02-25T15:29:58,301][INFO ][org.logstash.beats.BeatsHandler] [local: 0.0.0.0:5044, remote: undefined] Handling exception: javax.net.ssl.SSLHandshakeException: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER
[2020-02-25T15:29:58,303][WARN ][io.netty.channel.DefaultChannelPipeline] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:472) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: javax.net.ssl.SSLHandshakeException: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER
        at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.sslReadErrorResult(ReferenceCountedOpenSslEngine.java:1140) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1101) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1169) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1212) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.handler.ssl.SslHandler$SslEngineType$1.unwrap(SslHandler.java:216) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1297) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1211) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1245) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        ... 16 more
```
Without ssl works but with out it fails sending beats.

**Comment by MarcOverIP** [comment]
Perhaps a silly question, but did you restart the logstash and filebeat services after deploying the new certificates?

In my experience the exact error messages when dealing with SSL within the ELK stack are cryptic at best and most often do not really report what really is going on, except that there is something wrong with the TLS setup.

One thing that happens often is that the 'hosts' listed in the filebeat config is not the same as that was used for configuring the TLS certificates. And so it will fail. That is one thing you could check. 

Another thing is actually strictly define the versions numbers. I have never seen this to be an issue, but you could check. More info here: https://www.elastic.co/guide/en/logstash/current/plugins-inputs-beats.html#plugins-inputs-beats-tls_max_version

Another more generic walkthrough of setting this up can be found here: https://www.elastic.co/guide/en/beats/filebeat/current/configuring-ssl-logstash.html
Pay specific attention to the curl command that you can use to test the TLS connection and CA validation manually.

**Comment by trufardo** [comment]
I redo the cert command by command and add  ` ssl_verify_mode => none` in the 10-inputs.conf, now it works, by the script not work for me, maybe is a special case, thanks for your response.
